

spring:
  devtools:
    restart:
      enabled: true  # 热部署
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?useSSL=false&charactorEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: blog_db
    password: KL6pdcMn3CwfWxaC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    password:  RJMVNHFAKLLPHFEP
    username: enncyfunnyblog@163.com
    protocol: smtp
  security:
    user:
      name: enncy
      password: ll877526278
      roles: admin
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: /static/,/.well-known/

server:
  port: 8999  # 服务器启动端口


springfox:
  documentation:
    swagger-ui:
      enabled: true
      base-url:

logging:
  file:
    path: logs/